//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.11 at 08:41:59 PM CET 
//


package jaxbGenerated.datenxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}text"/>
 *         &lt;element ref="{}textkurz"/>
 *         &lt;element name="tarnidentitaet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "text",
    "textkurz",
    "tarnidentitaet"
})
@XmlRootElement(name = "profession")
public class Profession {

    @XmlElement(required = true)
    protected String text;
    @XmlElement(required = true)
    protected String textkurz;
    @XmlElement(required = true)
    protected String tarnidentitaet;

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textkurz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextkurz() {
        return textkurz;
    }

    /**
     * Sets the value of the textkurz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextkurz(String value) {
        this.textkurz = value;
    }

    /**
     * Gets the value of the tarnidentitaet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarnidentitaet() {
        return tarnidentitaet;
    }

    /**
     * Sets the value of the tarnidentitaet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarnidentitaet(String value) {
        this.tarnidentitaet = value;
    }

}
