//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.11 at 08:41:59 PM CET 
//


package jaxbGenerated.datenxml;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bezeichner"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}kommentar"/>
 *         &lt;element ref="{}namemitkommentar"/>
 *         &lt;element ref="{}istvorteil"/>
 *         &lt;element ref="{}istnachteil"/>
 *         &lt;element ref="{}wert" minOccurs="0"/>
 *         &lt;element ref="{}istschlechteeigenschaft" minOccurs="0"/>
 *         &lt;element ref="{}istgabe" minOccurs="0"/>
 *         &lt;element ref="{}bereich" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="auswahlen" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="auswahl" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="wert" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                             &lt;element name="kommentar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bezeichner",
    "name",
    "kommentar",
    "namemitkommentar",
    "istvorteil",
    "istnachteil",
    "wert",
    "istschlechteeigenschaft",
    "istgabe",
    "bereich",
    "auswahlen"
})
@XmlRootElement(name = "vorteil")
public class Vorteil {

    @XmlElement(required = true)
    protected String bezeichner;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String kommentar;
    @XmlElement(required = true)
    protected String namemitkommentar;
    protected boolean istvorteil;
    protected boolean istnachteil;
    protected BigInteger wert;
    protected Boolean istschlechteeigenschaft;
    protected Boolean istgabe;
    protected List<String> bereich;
    protected Vorteil.Auswahlen auswahlen;

    /**
     * Gets the value of the bezeichner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichner() {
        return bezeichner;
    }

    /**
     * Sets the value of the bezeichner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichner(String value) {
        this.bezeichner = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the kommentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKommentar() {
        return kommentar;
    }

    /**
     * Sets the value of the kommentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKommentar(String value) {
        this.kommentar = value;
    }

    /**
     * Gets the value of the namemitkommentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamemitkommentar() {
        return namemitkommentar;
    }

    /**
     * Sets the value of the namemitkommentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamemitkommentar(String value) {
        this.namemitkommentar = value;
    }

    /**
     * Gets the value of the istvorteil property.
     * 
     */
    public boolean isIstvorteil() {
        return istvorteil;
    }

    /**
     * Sets the value of the istvorteil property.
     * 
     */
    public void setIstvorteil(boolean value) {
        this.istvorteil = value;
    }

    /**
     * Gets the value of the istnachteil property.
     * 
     */
    public boolean isIstnachteil() {
        return istnachteil;
    }

    /**
     * Sets the value of the istnachteil property.
     * 
     */
    public void setIstnachteil(boolean value) {
        this.istnachteil = value;
    }

    /**
     * Gets the value of the wert property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWert() {
        return wert;
    }

    /**
     * Sets the value of the wert property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWert(BigInteger value) {
        this.wert = value;
    }

    /**
     * Gets the value of the istschlechteeigenschaft property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIstschlechteeigenschaft() {
        return istschlechteeigenschaft;
    }

    /**
     * Sets the value of the istschlechteeigenschaft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIstschlechteeigenschaft(Boolean value) {
        this.istschlechteeigenschaft = value;
    }

    /**
     * Gets the value of the istgabe property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIstgabe() {
        return istgabe;
    }

    /**
     * Sets the value of the istgabe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIstgabe(Boolean value) {
        this.istgabe = value;
    }

    /**
     * Gets the value of the bereich property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bereich property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBereich().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBereich() {
        if (bereich == null) {
            bereich = new ArrayList<String>();
        }
        return this.bereich;
    }

    /**
     * Gets the value of the auswahlen property.
     * 
     * @return
     *     possible object is
     *     {@link Vorteil.Auswahlen }
     *     
     */
    public Vorteil.Auswahlen getAuswahlen() {
        return auswahlen;
    }

    /**
     * Sets the value of the auswahlen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vorteil.Auswahlen }
     *     
     */
    public void setAuswahlen(Vorteil.Auswahlen value) {
        this.auswahlen = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="auswahl" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="wert" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="kommentar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auswahl"
    })
    public static class Auswahlen {

        protected List<Vorteil.Auswahlen.Auswahl> auswahl;

        /**
         * Gets the value of the auswahl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the auswahl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuswahl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Vorteil.Auswahlen.Auswahl }
         * 
         * 
         */
        public List<Vorteil.Auswahlen.Auswahl> getAuswahl() {
            if (auswahl == null) {
                auswahl = new ArrayList<Vorteil.Auswahlen.Auswahl>();
            }
            return this.auswahl;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="wert" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
         *         &lt;element name="kommentar" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "wert",
            "kommentar"
        })
        public static class Auswahl {

            protected String name;
            protected BigDecimal wert;
            protected String kommentar;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the wert property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getWert() {
                return wert;
            }

            /**
             * Sets the value of the wert property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setWert(BigDecimal value) {
                this.wert = value;
            }

            /**
             * Gets the value of the kommentar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKommentar() {
                return kommentar;
            }

            /**
             * Sets the value of the kommentar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKommentar(String value) {
                this.kommentar = value;
            }

        }

    }

}
